name: Continuous Integration

# Triggers execute all tests workflow on push or pull request events
on: [push, pull_request]
jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@master
      - uses: c-hive/gha-npm-cache@v1

      - name: Install node modules
        run: |
          npm install

      - name: Run test
        run: |
          npm test
