name: Continuous Integration

# Triggers execute all tests workflow on pull request events
on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
    paths:
      - "app/**"
jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create config file
        working-directory: ./app
        run: ./scripts/createConfig.sh
      - name: Run Tests
        run: |
          cd app
          npm install --legacy-peer-deps
          npm test
  lint:
    name: ESLint + JSDoc checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install deps
        working-directory: ./app
        run: npm install --legacy-peer-deps
      - name: Run ESLint with extended checks
        working-directory: ./app
        run: npx eslint $(git diff --name-only --relative origin/main HEAD . | grep -E '\.(js|jsx|ts|tsx)$'| xargs) -c .eslintrc.ci.js --no-error-on-unmatched-pattern
